version: '2'
services:
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - ${APP_PATH}/nginx/config:/config
      - ${APP_PATH}/nginx/logs:/var/log/nginx
      - ${PROJECT_PATH}/assets/nginx/rproxy.conf:/etc/nginx/http.d/rproxy.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  portainer:
    hostname: portainer
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${APP_PATH}/portainer/data:/data"
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    volumes:
      - ${APP_PATH}/syncthing/config:/config
      - ${APP_PATH}:/app-data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - MEM_LIMIT=$UNIFI_CTRLR__MEM_LIMIT
    volumes:
      - ${APP_PATH}/unifi-controller/config:/config
    ports:
      - 3478:3478/udp # UniFi STUN port
      - 10001:10001/udp # AP Discovery
      - 8080:8080 # Device communication
      - 8443:8443 # UniFi Web Admin port
      - 1900:1900/udp # Optional. Required for 'Make controller discoverable on L2 network' option
      - 8843:8843 # Optional. RUniFi Guest Portal HTTPS redirect port
      - 8880:8880 # Optional. RUniFi Guest Portal HTTP redirect port
      - 6789:6789 # Optional. For mobile throughput test
      - 5514:5514/udp # Optional. Remote syslog port
    restart: unless-stopped