version: '2'
services:
  portainer:
    hostname: portainer
    container_name: portainer
    image: portainer/portainer
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/$APP_PATH/portainer/data:/data"