version: "2.1"
services:
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - /$APP_PATH/unifi-controller/data:/config
    ports:
      # UniFi STUN port
      - 3478:3478/udp
      # AP Discovery
      - 10001:10001/udp
      # Device communication
      - 8080:8080
      # UniFi Web Admin port
      - 8443:8443
      # Optional. Required for 'Make controller discoverable on L2 network' option
      - 1900:1900/udp
      # Optional. RUniFi Guest Portal HTTPS redirect port
      - 8843:8843
      # Optional. RUniFi Guest Portal HTTP redirect port
      - 8880:8880
      # Optional. For mobile throughput test
      - 6789:6789
      # Optional. Remote syslog port
      - 5514:5514/udp #optional
    restart: unless-stopped